apiVersion: apps/v1
kind: Deployment
metadata:
  name: rubyapp
  labels:
    app: makerble
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: myapp
          image: docker.io/sauravkharat/rubyapp # Updated image location
          ports:
            - containerPort: 8080
