databases:
  - name: makerble
    databaseName: patients
    user: users
    plan: free

services:
  - type: web
    name: makerble
    runtime: ruby
    plan: free
    buildCommand: "./bin/render-build.sh"
    # preDeployCommand: "bundle exec rails db:migrate" # preDeployCommand only available on paid instance types
    startCommand: "bundle exec rails server"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: patients
          property: connectionString
      - key: 94a6132ce2b5b5ad20c0491d5a2962d7
        sync: false
      - key: WEB_CONCURRENCY
        value: 2 # sensible default
